version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    networks:
      - app-network
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_HOST=database
    depends_on:
      - database
    networks:
      - app-network
  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db
networks:
  app-network:
    driver: bridge
volumes:
  mongo_data:
