# A lightweight Python image as parent
From python:3.7-alpine
# Set the working directory to /app
WORKDIR /app
# Copy the python app fibo.py in the working directory
COPY fibo.py .
# Execute the python program fibo.py
CMD ["python", "fibo.py"]
