- name: Deploy a service on Docker Swarm
  hosts: manager1
  gather_facts: no
  tasks:
    - name: Ensure Docker Swarm is running
      community.docker.docker_swarm:
        state: present

    - name: Ensure Docker SDK for Python is installed
      ansible.builtin.apt:
        name: python3-docker
        state: present
      become: true

    - name: Deploy nginx service
      community.docker.docker_swarm_service:
        name: nginx
        image: nginx
        replicas: 3
        publish:
          - published_port: 8080
            target_port: 80
            protocol: tcp
            mode: ingress