version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: books
    ports:
      - '3306:3306'
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    networks:
      - app_network
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  db_data: