version: "2.0"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
  whoami-1:
    image: "containous/whoami"
    container_name: "whoami-1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-1.rule=Host(`example.com`)"
      - "traefik.http.routers.whoami-1.entrypoints=web"
      - "traefik.http.services.whoami-service.loadbalancer.server.port=80"
      
  whoami-2:
    image: "containous/whoami"
    container_name: "whoami-2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-2.rule=Host(`example.com`)"
      - "traefik.http.routers.whoami-2.entrypoints=web"
      - "traefik.http.services.whoami-service.loadbalancer.server.port=80"
