version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    environment:
      - MONGO_HOST=database
    depends_on:
      - database
    networks:
      - app-network
  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo_data:
    driver: local
