version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - tig_network
    volumes:
      - grafana_data:/var/lib/grafana
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - '8086:8086'
    networks:
      - tig_network
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=telegraf

  telegraf:
      image: telegraf:1.25
      container_name: telegraf
      networks:
        - tig_network
      depends_on:
        - influxdb
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        - /:/hostfs:ro
      environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs

networks:
  tig_network:
    driver: bridge
volumes:
  grafana_data:
  influxdb_data: