version: '3'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - products-api
      - users-api
    networks:
      - api-network

  products-api:
    build:
      context: ./products-api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - api-network

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
