version: '2.0'

services:

 webadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
    links:
    - db
 db:
    image: mysql:8.0
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: secret
